{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "0878e6c8",
   "metadata": {},
   "source": [
    "Introduction"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "828009a8",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-12-05 19:57:51,183\tINFO services.py:1338 -- View the Ray dashboard at \u001b[1m\u001b[32mhttp://127.0.0.1:8265\u001b[39m\u001b[22m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'col1': 0, 'col2': '0'}\n",
      "{'col1': 1, 'col2': '1'}\n",
      "{'col1': 2, 'col2': '2'}\n",
      "{'col1': 3, 'col2': '3'}\n",
      "{'col1': 4, 'col2': '4'}\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "col1: int64\n",
       "col2: string"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import ray\n",
    "\n",
    "# Create a Dataset of Python objects.\n",
    "ds = ray.data.range(200)\n",
    "# -> Dataset(num_blocks=200, num_rows=10000, schema=<class 'int'>)\n",
    "\n",
    "ds.take(5)\n",
    "# -> [0, 1, 2, 3, 4]\n",
    "\n",
    "ds.count()\n",
    "# -> 10000\n",
    "\n",
    "# Create a Dataset of Arrow records.\n",
    "ds = ray.data.from_items([{\"col1\": i, \"col2\": str(i)} for i in range(200)])\n",
    "# -> Dataset(num_blocks=200, num_rows=10000, schema={col1: int64, col2: string})\n",
    "\n",
    "ds.show(5)\n",
    "# -> {'col1': 0, 'col2': '0'}\n",
    "# -> {'col1': 1, 'col2': '1'}\n",
    "# -> {'col1': 2, 'col2': '2'}\n",
    "# -> {'col1': 3, 'col2': '3'}\n",
    "# -> {'col1': 4, 'col2': '4'}\n",
    "\n",
    "ds.schema()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "d54c3623",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import dask.dataframe as dd\n",
    "\n",
    "# Create a Dataset from a list of Pandas DataFrame objects.\n",
    "pdf = pd.DataFrame({\"one\": [1, 2, 3], \"two\": [\"a\", \"b\", \"c\"]})\n",
    "ds = ray.data.from_pandas([pdf])\n",
    "\n",
    "# Create a Dataset from a Dask-on-Ray DataFrame.\n",
    "dask_df = dd.from_pandas(pdf, npartitions=10)\n",
    "ds = ray.data.from_dask(dask_df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "1b210e05",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Map Progress: 100%|██████████| 200/200 [00:00<00:00, 324.52it/s]\n",
      "Map Progress: 100%|██████████| 200/200 [00:00<00:00, 481.75it/s]\n",
      "Map Progress: 100%|██████████| 200/200 [00:00<00:00, 425.79it/s]\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "[0, 0, 2, -2, 4]"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "ds = ray.data.range(10000)\n",
    "ds = ds.map(lambda x: x * 2)\n",
    "# -> Map Progress: 100%|████████████████████| 200/200 [00:00<00:00, 1123.54it/s]\n",
    "# -> Dataset(num_blocks=200, num_rows=10000, schema=<class 'int'>)\n",
    "ds.take(5)\n",
    "# -> [0, 2, 4, 6, 8]\n",
    "\n",
    "ds.filter(lambda x: x > 5).take(5)\n",
    "# -> Map Progress: 100%|████████████████████| 200/200 [00:00<00:00, 1859.63it/s]\n",
    "# -> [6, 8, 10, 12, 14]\n",
    "\n",
    "ds.flat_map(lambda x: [x, -x]).take(5)\n",
    "# -> Map Progress: 100%|████████████████████| 200/200 [00:00<00:00, 1568.10it/s]\n",
    "# -> [0, 0, 2, -2, 4]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "9fe4fa72",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Map Progress: 100%|██████████| 200/200 [00:01<00:00, 131.55it/s]\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "[{'value': 0}, {'value': 2}, {'value': 4}, {'value': 6}, {'value': 8}]"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "ds = ray.data.range_arrow(10000)\n",
    "ds = ds.map_batches(\n",
    "    lambda df: df.applymap(lambda x: x * 2), batch_format=\"pandas\")\n",
    "# -> Map Progress: 100%|████████████████████| 200/200 [00:00<00:00, 1927.62it/s]\n",
    "ds.take(5)\n",
    "# -> [{'value': 0}, {'value': 2}, ...]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "6f212f63",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "200"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "@ray.remote\n",
    "def consume(data) -> int:\n",
    "    num_batches = 0\n",
    "    for batch in data.iter_batches():\n",
    "        num_batches += 1\n",
    "    return num_batches\n",
    "\n",
    "ds = ray.data.range(10000)\n",
    "ray.get(consume.remote(ds))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "b784a3af",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'w' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp/ipykernel_3304/3655161914.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m     19\u001b[0m \u001b[1;31m#     Dataset(num_blocks=13, num_rows=650, schema=<class 'int'>), ...]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     20\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 21\u001b[1;33m \u001b[0mray\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m[\u001b[0m\u001b[0mw\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtrain\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mremote\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0ms\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;32mfor\u001b[0m \u001b[0ms\u001b[0m \u001b[1;32min\u001b[0m \u001b[0mshards\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;32m~\\AppData\\Local\\Temp/ipykernel_3304/3655161914.py\u001b[0m in \u001b[0;36m<listcomp>\u001b[1;34m(.0)\u001b[0m\n\u001b[0;32m     19\u001b[0m \u001b[1;31m#     Dataset(num_blocks=13, num_rows=650, schema=<class 'int'>), ...]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     20\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 21\u001b[1;33m \u001b[0mray\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m[\u001b[0m\u001b[0mw\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtrain\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mremote\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0ms\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;32mfor\u001b[0m \u001b[0ms\u001b[0m \u001b[1;32min\u001b[0m \u001b[0mshards\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m: name 'w' is not defined"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[1m\u001b[36m(scheduler +40s)\u001b[0m Tip: use `ray status` to view detailed cluster status. To disable these messages, set RAY_SCHEDULER_EVENTS=0.\n",
      "\u001b[2m\u001b[1m\u001b[33m(scheduler +40s)\u001b[0m Warning: The following resource request cannot be scheduled right now: {'CPU': 1.0, 'GPU': 1.0}. This is likely due to all cluster resources being claimed by actors. Consider creating fewer actors or adding more nodes to this Ray cluster.\r\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-12-05 19:58:31,739\tWARNING worker.py:1245 -- The actor or task with ID ffffffffffffffff8764f7827bbd189d6e832eb401000000 cannot be scheduled right now. You can ignore this message if this Ray cluster is expected to auto-scale or if you specified a runtime_env for this actor or task, which may take time to install.  Otherwise, this is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increasing the resources available to this Ray cluster.\n",
      "Required resources for this actor or task: {CPU: 1.000000}, {GPU: 1.000000}\n",
      "Available resources on this node: {3.000000/4.000000 CPU, 77736960.058594 GiB/77736960.058594 GiB memory, 0.000000/1.000000 GPU, 38868479.980469 GiB/38868479.980469 GiB object_store_memory, 1.000000/1.000000 node:127.0.0.1}\n",
      " In total there are 0 pending tasks and 15 pending actors on this node.\n"
     ]
    }
   ],
   "source": [
    "@ray.remote(num_gpus=1)\n",
    "class Worker:\n",
    "    def __init__(self, rank: int):\n",
    "        pass\n",
    "\n",
    "    def train(self, shard: ray.data.Dataset[int]) -> int:\n",
    "        for batch in shard.iter_batches(batch_size=256):\n",
    "            pass\n",
    "        return shard.count()\n",
    "\n",
    "workers = [Worker.remote(i) for i in range(16)]\n",
    "# -> [Actor(Worker, ...), Actor(Worker, ...), ...]\n",
    "\n",
    "ds = ray.data.range(10000)\n",
    "# -> Dataset(num_blocks=200, num_rows=10000, schema=<class 'int'>)\n",
    "\n",
    "shards = ds.split(n=16, locality_hints=workers)\n",
    "# -> [Dataset(num_blocks=13, num_rows=650, schema=<class 'int'>),\n",
    "#     Dataset(num_blocks=13, num_rows=650, schema=<class 'int'>), ...]\n",
    "\n",
    "ray.get([w.train.remote(s) for s in shards])"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "61780011",
   "metadata": {},
   "source": [
    "Pipelines"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "50425b53",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Stage 0:   0%|          | 0/20 [00:00<?, ?it/s]\n",
      "  0%|          | 0/20 [00:00<?, ?it/s]\u001b[A\n",
      "Stage 1:   0%|          | 0/20 [00:00<?, ?it/s]\u001b[A\n",
      "\n",
      "  0%|          | 0/20 [00:00<?, ?it/s]\u001b[A\u001b[A\n",
      "\n",
      "Stage 2:   0%|          | 0/20 [00:00<?, ?it/s]\u001b[A\u001b[A\n",
      "\n",
      "\n",
      "  0%|          | 0/20 [00:00<?, ?it/s]\u001b[A\u001b[A\u001b[A\n",
      "\n",
      "\n",
      "Stage 3:   0%|          | 0/20 [00:00<?, ?it/s]\u001b[A\u001b[A\u001b[A"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dataset(num_blocks=200, num_rows=1000000, schema=<class 'int'>)\n",
      "DatasetPipeline(num_windows=20, num_stages=1)\n",
      "DatasetPipeline(num_windows=20, num_stages=4)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "Stage 0:  10%|█         | 2/20 [00:00<00:02,  6.11it/s]\u001b[A\n",
      "\n",
      "Stage 2:   5%|▌         | 1/20 [00:00<00:10,  1.85it/s]\u001b[A\u001b[A\n",
      "Stage 0:  15%|█▌        | 3/20 [00:00<00:04,  3.44it/s]\u001b[A\n",
      "\n",
      "\n",
      "Stage 3:   5%|▌         | 1/20 [00:00<00:16,  1.13it/s]\u001b[A\u001b[A\u001b[A\n",
      "\n",
      "Stage 2:  10%|█         | 2/20 [00:01<00:09,  1.96it/s]\u001b[A\u001b[A\n",
      "\n",
      "\n",
      "Stage 3:  10%|█         | 2/20 [00:01<00:11,  1.56it/s]\u001b[A\u001b[A\u001b[A\n",
      "Stage 0:  20%|██        | 4/20 [00:01<00:07,  2.22it/s]\u001b[A\n",
      "\n",
      "Stage 2:  15%|█▌        | 3/20 [00:01<00:10,  1.66it/s]\u001b[A\u001b[A\n",
      "\n",
      "\n",
      "Stage 3:  15%|█▌        | 3/20 [00:01<00:10,  1.62it/s]\u001b[A\u001b[A\u001b[A\n",
      "Stage 0:  25%|██▌       | 5/20 [00:02<00:07,  1.97it/s]\u001b[A\n",
      "\n",
      "Stage 2:  20%|██        | 4/20 [00:02<00:09,  1.66it/s]\u001b[A\u001b[A\n",
      "\n",
      "\n",
      "Stage 3:  20%|██        | 4/20 [00:02<00:10,  1.53it/s]\u001b[A\u001b[A\u001b[A\n",
      "Stage 0:  30%|███       | 6/20 [00:02<00:07,  1.76it/s]\u001b[A\n",
      "\n",
      "Stage 2:  25%|██▌       | 5/20 [00:03<00:10,  1.45it/s]\u001b[A\u001b[A\n",
      "Stage 0:  35%|███▌      | 7/20 [00:03<00:07,  1.70it/s]\u001b[A\n",
      "\n",
      "\n",
      "Stage 3:  25%|██▌       | 5/20 [00:03<00:11,  1.29it/s]\u001b[A\u001b[A\u001b[A\n",
      "\n",
      "Stage 2:  30%|███       | 6/20 [00:03<00:09,  1.52it/s]\u001b[A\u001b[A\n",
      "\n",
      "\n",
      "Stage 3:  30%|███       | 6/20 [00:03<00:08,  1.59it/s]\u001b[A\u001b[A\u001b[A\n",
      "Stage 0:  40%|████      | 8/20 [00:04<00:07,  1.61it/s]\u001b[A\n",
      "\n",
      "Stage 2:  35%|███▌      | 7/20 [00:04<00:08,  1.59it/s]\u001b[A\u001b[A\n",
      "\n",
      "\n",
      "Stage 3:  35%|███▌      | 7/20 [00:04<00:07,  1.64it/s]\u001b[A\u001b[A\u001b[A\n",
      "Stage 0:  45%|████▌     | 9/20 [00:04<00:06,  1.60it/s]\u001b[A\n",
      "\n",
      "Stage 2:  40%|████      | 8/20 [00:04<00:07,  1.58it/s]\u001b[A\u001b[A\n",
      "\n",
      "\n",
      "Stage 3:  40%|████      | 8/20 [00:05<00:07,  1.61it/s]\u001b[A\u001b[A\u001b[A\n",
      "Stage 0:  50%|█████     | 10/20 [00:05<00:06,  1.65it/s][A\n",
      "\n",
      "Stage 2:  45%|████▌     | 9/20 [00:05<00:07,  1.54it/s]\u001b[A\u001b[A\n",
      "\n",
      "\n",
      "Stage 3:  45%|████▌     | 9/20 [00:05<00:06,  1.58it/s]\u001b[A\u001b[A\u001b[A\n",
      "Stage 0:  55%|█████▌    | 11/20 [00:05<00:05,  1.68it/s]\u001b[A\n",
      "\n",
      "Stage 2:  50%|█████     | 10/20 [00:06<00:05,  1.68it/s]\u001b[A\u001b[A\n",
      "Stage 0:  60%|██████    | 12/20 [00:06<00:04,  1.90it/s]\u001b[A\n",
      "\n",
      "\n",
      "Stage 3:  50%|█████     | 10/20 [00:06<00:06,  1.59it/s]\u001b[A\u001b[A\u001b[A\n",
      "\n",
      "Stage 2:  55%|█████▌    | 11/20 [00:06<00:05,  1.80it/s]\u001b[A\u001b[A\n",
      "\n",
      "\n",
      "Stage 3:  55%|█████▌    | 11/20 [00:06<00:04,  1.84it/s]\u001b[A\u001b[A\u001b[A\n",
      "Stage 0:  65%|██████▌   | 13/20 [00:06<00:03,  1.77it/s]\u001b[A\n",
      "\n",
      "Stage 2:  60%|██████    | 12/20 [00:07<00:04,  1.83it/s]\u001b[A\u001b[A\n",
      "\n",
      "\n",
      "Stage 3:  60%|██████    | 12/20 [00:07<00:04,  1.76it/s]\u001b[A\u001b[A\u001b[A\n",
      "Stage 0:  70%|███████   | 14/20 [00:07<00:03,  1.68it/s]\u001b[A\n",
      "\n",
      "Stage 2:  65%|██████▌   | 13/20 [00:07<00:04,  1.72it/s]\u001b[A\u001b[A\n",
      "Stage 0:  75%|███████▌  | 15/20 [00:08<00:02,  1.82it/s]\u001b[A\n",
      "\n",
      "\n",
      "Stage 3:  65%|██████▌   | 13/20 [00:08<00:04,  1.67it/s]\u001b[A\u001b[A\u001b[A\n",
      "\n",
      "Stage 2:  70%|███████   | 14/20 [00:08<00:03,  1.83it/s]\u001b[A\u001b[A\n",
      "Stage 0:  80%|████████  | 16/20 [00:08<00:02,  1.91it/s]\u001b[A\n",
      "\n",
      "\n",
      "Stage 3:  70%|███████   | 14/20 [00:08<00:03,  1.79it/s]\u001b[A\u001b[A\u001b[A\n",
      "\n",
      "Stage 2:  75%|███████▌  | 15/20 [00:08<00:02,  1.92it/s]\u001b[A\u001b[A\n",
      "\n",
      "\n",
      "Stage 3:  75%|███████▌  | 15/20 [00:08<00:02,  2.03it/s]\u001b[A\u001b[A\u001b[A\n",
      "Stage 0:  85%|████████▌ | 17/20 [00:09<00:01,  1.88it/s]\u001b[A\n",
      "\n",
      "Stage 2:  80%|████████  | 16/20 [00:09<00:02,  1.92it/s]\u001b[A\u001b[A\n",
      "\n",
      "\n",
      "Stage 3:  80%|████████  | 16/20 [00:09<00:02,  1.98it/s]\u001b[A\u001b[A\u001b[A\n",
      "Stage 0:  90%|█████████ | 18/20 [00:09<00:01,  1.89it/s]\u001b[A\n",
      "\n",
      "Stage 2:  85%|████████▌ | 17/20 [00:09<00:01,  1.92it/s]\u001b[A\u001b[A\n",
      "\n",
      "\n",
      "Stage 3:  85%|████████▌ | 17/20 [00:09<00:01,  1.97it/s]\u001b[A\u001b[A\u001b[A\n",
      "Stage 0:  95%|█████████▌| 19/20 [00:10<00:00,  1.78it/s]\u001b[A\n",
      "\n",
      "Stage 2:  90%|█████████ | 18/20 [00:10<00:01,  1.79it/s]\u001b[A\u001b[A\n",
      "Stage 0: 100%|██████████| 20/20 [00:10<00:00,  2.03it/s]\u001b[A\n",
      "\n",
      "\n",
      "Stage 3:  90%|█████████ | 18/20 [00:10<00:01,  1.82it/s]\u001b[A\u001b[A\u001b[A\n",
      "\n",
      "Stage 2:  95%|█████████▌| 19/20 [00:10<00:00,  2.03it/s]\u001b[A\u001b[A\n",
      "\n",
      "\n",
      "Stage 3:  95%|█████████▌| 19/20 [00:11<00:00,  1.94it/s]\u001b[A\u001b[A\u001b[A\n",
      "Stage 1: 100%|██████████| 20/20 [00:11<00:00,  1.93it/s]\u001b[A\n",
      "\n",
      "Stage 2: 100%|██████████| 20/20 [00:11<00:00,  2.05it/s]\u001b[A\u001b[A\n",
      "\n",
      "\n",
      "Stage 3: 100%|██████████| 20/20 [00:11<00:00,  1.76it/s]\u001b[A\u001b[A\u001b[A\n",
      "Stage 2: 100%|██████████| 20/20 [00:11<00:00,  1.76it/s]\n",
      "Stage 1: 100%|██████████| 20/20 [00:11<00:00,  1.75it/s]\n",
      "Stage 0: 100%|██████████| 20/20 [00:11<00:00,  1.75it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Total num rows 1000000\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[1m\u001b[33m(scheduler +3m30s)\u001b[0m Warning: The following resource request cannot be scheduled right now: {'GPU': 1.0, 'CPU': 1.0}. This is likely due to all cluster resources being claimed by actors. Consider creating fewer actors or adding more nodes to this Ray cluster.\r\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-12-05 19:39:32,851\tWARNING worker.py:1245 -- The actor or task with ID fffffffffffffffff2a4a5104568b5c8a91d5f4001000000 cannot be scheduled right now. You can ignore this message if this Ray cluster is expected to auto-scale or if you specified a runtime_env for this actor or task, which may take time to install.  Otherwise, this is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increasing the resources available to this Ray cluster.\n",
      "Required resources for this actor or task: {CPU: 1.000000}, {GPU: 1.000000}\n",
      "Available resources on this node: {3.000000/4.000000 CPU, 86470680.029297 GiB/86470680.029297 GiB memory, 0.000000/1.000000 GPU, 43235339.990234 GiB/43235339.990234 GiB object_store_memory, 1.000000/1.000000 node:127.0.0.1}\n",
      " In total there are 0 pending tasks and 15 pending actors on this node.\n"
     ]
    }
   ],
   "source": [
    "def func1(i: int) -> int:\n",
    "    return i + 1\n",
    "\n",
    "def func2(i: int) -> int:\n",
    "    return i * 2\n",
    "\n",
    "def func3(i: int) -> int:\n",
    "    return i % 3\n",
    "\n",
    "# Create a dataset and then create a pipeline from it.\n",
    "base = ray.data.range(1000000)\n",
    "print(base)\n",
    "# -> Dataset(num_blocks=200, num_rows=1000000, schema=<class 'int'>)\n",
    "pipe = base.window(blocks_per_window=10)\n",
    "print(pipe)\n",
    "# -> DatasetPipeline(num_windows=20, num_stages=1)\n",
    "\n",
    "# Applying transforms to pipelines adds more pipeline stages.\n",
    "pipe = pipe.map(func1)\n",
    "pipe = pipe.map(func2)\n",
    "pipe = pipe.map(func3)\n",
    "print(pipe)\n",
    "# -> DatasetPipeline(num_windows=20, num_stages=4)\n",
    "\n",
    "# Output can be pulled from the pipeline concurrently with its execution.\n",
    "num_rows = 0\n",
    "for row in pipe.iter_rows():\n",
    "    num_rows += 1\n",
    "\n",
    "print(\"Total num rows\", num_rows)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "eea19330",
   "metadata": {},
   "outputs": [],
   "source": [
    "import ray\n",
    "from ray.data.dataset_pipeline import DatasetPipeline\n",
    "\n",
    "# Equivalent to ray.data.range(1000).repeat(times=4)\n",
    "source = ray.data.range(1000)\n",
    "pipe = DatasetPipeline.from_iterable(\n",
    "    [lambda: source, lambda: source, lambda: source, lambda: source])\n",
    "\n",
    "# Equivalent to ray.data.range(1000).window(blocks_per_window=10)\n",
    "splits = ray.data.range(1000, parallelism=200).split(20)\n",
    "pipe = DatasetPipeline.from_iterable([lambda s=s: s for s in splits])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "8a01223e",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Stage 0:   0%|          | 0/3 [00:00<?, ?it/s]\n",
      "  0%|          | 0/3 [00:00<?, ?it/s]\u001b[A\n",
      "Stage 1:   0%|          | 0/3 [00:00<?, ?it/s]\u001b[A\n",
      "Stage 0: 100%|██████████| 1/1 [00:00<00:00, 12.60it/s]\u001b[A\n",
      "Stage 0:   0%|          | 0/1 [00:00<?, ?it/s]\n",
      "Stage 0: 100%|██████████| 1/1 [00:00<00:00, 16.07it/s]\u001b[A\n",
      "Stage 0: 100%|██████████| 1/1 [00:00<00:00, 72.91it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch {} 0\n",
      "4\n",
      "3\n",
      "0\n",
      "1\n",
      "2\n",
      "Epoch {} 1\n",
      "0\n",
      "1\n",
      "3\n",
      "2\n",
      "4\n",
      "Epoch {} 2\n",
      "0\n",
      "2\n",
      "3\n",
      "4\n",
      "1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[1m\u001b[33m(scheduler +4m6s)\u001b[0m Warning: The following resource request cannot be scheduled right now: {'CPU': 1.0, 'GPU': 1.0}. This is likely due to all cluster resources being claimed by actors. Consider creating fewer actors or adding more nodes to this Ray cluster.\r\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Stage 0: 100%|██████████| 3/3 [00:10<00:00, 14.58it/s]\n",
      "Stage 1: 100%|██████████| 3/3 [00:10<00:00, 10.97it/s]\u001b[A"
     ]
    }
   ],
   "source": [
    "pipe = ray.data.from_items([0, 1, 2, 3, 4]) \\\n",
    "    .repeat(3) \\\n",
    "    .random_shuffle_each_window()\n",
    "for i, epoch in enumerate(pipe.iter_epochs()):\n",
    "    print(\"Epoch {}\", i)\n",
    "    for row in epoch.iter_rows():\n",
    "        print(row)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "c05ef322",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Stage 0:   0%|          | 0/2 [00:00<?, ?it/s]\n",
      "  0%|          | 0/2 [00:00<?, ?it/s]\u001b[A\n",
      "Stage 1:   0%|          | 0/2 [00:00<?, ?it/s]\u001b[A\n",
      "Stage 1: 100%|██████████| 2/2 [00:00<00:00, 10.01it/s]\u001b[A\n",
      "Stage 0: 100%|██████████| 2/2 [00:00<00:00,  9.60it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "------ Epoch 0 ------\n",
      "=== Window 0 ===\n",
      "3\n",
      "2\n",
      "0\n",
      "1\n",
      "4\n",
      "------ Epoch 1 ------\n",
      "=== Window 1 ===\n",
      "3\n",
      "0\n",
      "4\n",
      "1\n",
      "2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "ray.data.from_items([0, 1, 2, 3, 4]) \\\n",
    "    .repeat(2) \\\n",
    "    .random_shuffle_each_window() \\\n",
    "    .show_windows()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "a0c3989c",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Stage 0:   0%|          | 0/2 [00:00<?, ?it/s]\n",
      "  0%|          | 0/2 [00:00<?, ?it/s]\u001b[A\n",
      "Stage 1:   0%|          | 0/2 [00:00<?, ?it/s]\u001b[A\n",
      "Stage 1: 100%|██████████| 2/2 [00:00<00:00, 14.08it/s]\u001b[A\n",
      "Stage 0: 100%|██████████| 2/2 [00:00<00:00, 13.61it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "------ Epoch 0 ------\n",
      "=== Window 0 ===\n",
      "0\n",
      "1\n",
      "4\n",
      "3\n",
      "2\n",
      "------ Epoch 1 ------\n",
      "=== Window 1 ===\n",
      "2\n",
      "3\n",
      "0\n",
      "1\n",
      "4\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "ray.data.from_items([0, 1, 2, 3, 4]) \\\n",
    "    .repeat(2) \\\n",
    "    .foreach_window(lambda w: w.random_shuffle()) \\\n",
    "    .show_windows()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "87527fe0",
   "metadata": {},
   "outputs": [
    {
     "ename": "OSError",
     "evalue": "When getting information for key 'image-dir' in bucket 'bucket': AWS Error [code 15]: No response body.",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mOSError\u001b[0m                                   Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp/ipykernel_14428/2740895280.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      9\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     10\u001b[0m \u001b[1;31m# Load data from storage.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 11\u001b[1;33m \u001b[0mds\u001b[0m\u001b[1;33m:\u001b[0m \u001b[0mDataset\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mray\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mdata\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mread_binary_files\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"s3://bucket/image-dir\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     12\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     13\u001b[0m \u001b[1;31m# Preprocess the data.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\read_api.py\u001b[0m in \u001b[0;36mread_binary_files\u001b[1;34m(paths, include_paths, filesystem, parallelism, ray_remote_args, arrow_open_stream_args)\u001b[0m\n\u001b[0;32m    481\u001b[0m         \u001b[0mDataset\u001b[0m \u001b[0mholding\u001b[0m \u001b[0mArrow\u001b[0m \u001b[0mrecords\u001b[0m \u001b[0mread\u001b[0m \u001b[1;32mfrom\u001b[0m \u001b[0mthe\u001b[0m \u001b[0mspecified\u001b[0m \u001b[0mpaths\u001b[0m\u001b[1;33m.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    482\u001b[0m     \"\"\"\n\u001b[1;32m--> 483\u001b[1;33m     return read_datasource(\n\u001b[0m\u001b[0;32m    484\u001b[0m         \u001b[0mBinaryDatasource\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    485\u001b[0m         \u001b[0mparallelism\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mparallelism\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\read_api.py\u001b[0m in \u001b[0;36mread_datasource\u001b[1;34m(datasource, parallelism, ray_remote_args, _spread_resource_prefix, **read_args)\u001b[0m\n\u001b[0;32m    159\u001b[0m     \"\"\"\n\u001b[0;32m    160\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 161\u001b[1;33m     \u001b[0mread_tasks\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mdatasource\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mprepare_read\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mparallelism\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mread_args\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    162\u001b[0m     \u001b[0mcontext\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mDatasetContext\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget_current\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    163\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\datasource\\file_based_datasource.py\u001b[0m in \u001b[0;36mprepare_read\u001b[1;34m(self, parallelism, paths, filesystem, schema, open_stream_args, _block_udf, **reader_args)\u001b[0m\n\u001b[0;32m    125\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    126\u001b[0m         \u001b[0mpaths\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfilesystem\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0m_resolve_paths_and_filesystem\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mpaths\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfilesystem\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 127\u001b[1;33m         \u001b[0mpaths\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfile_infos\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0m_expand_paths\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mpaths\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfilesystem\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    128\u001b[0m         \u001b[0mfile_sizes\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;33m[\u001b[0m\u001b[0mfile_info\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msize\u001b[0m \u001b[1;32mfor\u001b[0m \u001b[0mfile_info\u001b[0m \u001b[1;32min\u001b[0m \u001b[0mfile_infos\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    129\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\datasource\\file_based_datasource.py\u001b[0m in \u001b[0;36m_expand_paths\u001b[1;34m(paths, filesystem)\u001b[0m\n\u001b[0;32m    366\u001b[0m     \u001b[0mfile_infos\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;33m[\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    367\u001b[0m     \u001b[1;32mfor\u001b[0m \u001b[0mpath\u001b[0m \u001b[1;32min\u001b[0m \u001b[0mpaths\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 368\u001b[1;33m         \u001b[0mfile_info\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mfilesystem\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget_file_info\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mpath\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    369\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mfile_info\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtype\u001b[0m \u001b[1;33m==\u001b[0m \u001b[0mFileType\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mDirectory\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    370\u001b[0m             \u001b[0mpaths\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfile_infos_\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0m_expand_directory\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mpath\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfilesystem\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\pyarrow\\_fs.pyx\u001b[0m in \u001b[0;36mpyarrow._fs.FileSystem.get_file_info\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;32mD:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\pyarrow\\error.pxi\u001b[0m in \u001b[0;36mpyarrow.lib.pyarrow_internal_check_status\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;32mD:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\pyarrow\\error.pxi\u001b[0m in \u001b[0;36mpyarrow.lib.check_status\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mOSError\u001b[0m: When getting information for key 'image-dir' in bucket 'bucket': AWS Error [code 15]: No response body."
     ]
    }
   ],
   "source": [
    "def preprocess(image: bytes) -> bytes:\n",
    "    return image\n",
    "\n",
    "class BatchInferModel:\n",
    "    def __init__(self):\n",
    "        self.model = ImageNetModel()\n",
    "    def __call__(self, batch: pd.DataFrame) -> pd.DataFrame:\n",
    "        return self.model(batch)\n",
    "\n",
    "# Load data from storage.\n",
    "ds: Dataset = ray.data.read_binary_files(\"s3://bucket/image-dir\")\n",
    "\n",
    "# Preprocess the data.\n",
    "ds = ds.map(preprocess)\n",
    "\n",
    "# Apply GPU batch inference to the data.\n",
    "ds = ds.map_batches(BatchInferModel, compute=\"actors\", batch_size=256, num_gpus=1)\n",
    "ds\n",
    "# Save the output.\n",
    "#ds.write_json(\"/tmp/results\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "fd35a4de",
   "metadata": {},
   "outputs": [
    {
     "ename": "AttributeError",
     "evalue": "'ellipsis' object has no attribute 'prepare_read'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp/ipykernel_14428/2073455404.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[1;31m# Create a pipeline that loops over its source dataset indefinitely.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 2\u001b[1;33m \u001b[0mpipe\u001b[0m\u001b[1;33m:\u001b[0m \u001b[0mDatasetPipeline\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mray\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mdata\u001b[0m\u001b[0;31m \u001b[0m\u001b[0;31m\\\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      3\u001b[0m     \u001b[1;33m.\u001b[0m\u001b[0mread_datasource\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m...\u001b[0m\u001b[1;33m)\u001b[0m\u001b[0;31m \u001b[0m\u001b[0;31m\\\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      4\u001b[0m     \u001b[1;33m.\u001b[0m\u001b[0mrepeat\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[0;31m \u001b[0m\u001b[0;31m\\\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      5\u001b[0m     \u001b[1;33m.\u001b[0m\u001b[0mrandom_shuffle_each_window\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\read_api.py\u001b[0m in \u001b[0;36mread_datasource\u001b[1;34m(datasource, parallelism, ray_remote_args, _spread_resource_prefix, **read_args)\u001b[0m\n\u001b[0;32m    159\u001b[0m     \"\"\"\n\u001b[0;32m    160\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 161\u001b[1;33m     \u001b[0mread_tasks\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mdatasource\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mprepare_read\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mparallelism\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mread_args\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    162\u001b[0m     \u001b[0mcontext\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mDatasetContext\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget_current\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    163\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mAttributeError\u001b[0m: 'ellipsis' object has no attribute 'prepare_read'"
     ]
    }
   ],
   "source": [
    "# Create a pipeline that loops over its source dataset indefinitely.\n",
    "pipe: DatasetPipeline = ray.data \\\n",
    "    .read_datasource(...) \\\n",
    "    .repeat() \\\n",
    "    .random_shuffle_each_window()\n",
    "\n",
    "@ray.remote(num_gpus=1)\n",
    "def train_func(pipe: DatasetPipeline):\n",
    "    model = MyModel()\n",
    "    for batch in pipe.to_torch():\n",
    "        model.fit(batch)\n",
    "\n",
    "# Read from the pipeline in a remote training function.\n",
    "ray.get(train_func.remote(pipe))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "f47c4eba",
   "metadata": {},
   "outputs": [
    {
     "ename": "ValueError",
     "evalue": "paths must be a path string or a list of path strings.",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp/ipykernel_13152/791357472.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      7\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      8\u001b[0m \u001b[1;31m# Create a pipeline that loops over its source dataset indefinitely.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 9\u001b[1;33m \u001b[0mpipe\u001b[0m\u001b[1;33m:\u001b[0m \u001b[0mDatasetPipeline\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mray\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mdata\u001b[0m\u001b[0;31m \u001b[0m\u001b[0;31m\\\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     10\u001b[0m     \u001b[1;33m.\u001b[0m\u001b[0mread_parquet\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m...\u001b[0m\u001b[1;33m)\u001b[0m\u001b[0;31m \u001b[0m\u001b[0;31m\\\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     11\u001b[0m     \u001b[1;33m.\u001b[0m\u001b[0mrepeat\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[0;31m \u001b[0m\u001b[0;31m\\\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\read_api.py\u001b[0m in \u001b[0;36mread_parquet\u001b[1;34m(paths, filesystem, columns, parallelism, ray_remote_args, _tensor_column_schema, **arrow_parquet_args)\u001b[0m\n\u001b[0;32m    269\u001b[0m         \u001b[0marrow_parquet_args\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m\"_block_udf\"\u001b[0m\u001b[1;33m]\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0m_block_udf\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    270\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 271\u001b[1;33m     return read_datasource(\n\u001b[0m\u001b[0;32m    272\u001b[0m         \u001b[0mParquetDatasource\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    273\u001b[0m         \u001b[0mparallelism\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mparallelism\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\read_api.py\u001b[0m in \u001b[0;36mread_datasource\u001b[1;34m(datasource, parallelism, ray_remote_args, _spread_resource_prefix, **read_args)\u001b[0m\n\u001b[0;32m    159\u001b[0m     \"\"\"\n\u001b[0;32m    160\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 161\u001b[1;33m     \u001b[0mread_tasks\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mdatasource\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mprepare_read\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mparallelism\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mread_args\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    162\u001b[0m     \u001b[0mcontext\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mDatasetContext\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget_current\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    163\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\datasource\\parquet_datasource.py\u001b[0m in \u001b[0;36mprepare_read\u001b[1;34m(self, parallelism, paths, filesystem, columns, schema, _block_udf, **reader_args)\u001b[0m\n\u001b[0;32m     54\u001b[0m         \u001b[1;32mimport\u001b[0m \u001b[0mnumpy\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0mnp\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     55\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 56\u001b[1;33m         \u001b[0mpaths\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfilesystem\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0m_resolve_paths_and_filesystem\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mpaths\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfilesystem\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     57\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mlen\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mpaths\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;33m==\u001b[0m \u001b[1;36m1\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     58\u001b[0m             \u001b[0mpaths\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mpaths\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\datasource\\file_based_datasource.py\u001b[0m in \u001b[0;36m_resolve_paths_and_filesystem\u001b[1;34m(paths, filesystem)\u001b[0m\n\u001b[0;32m    300\u001b[0m     elif (not isinstance(paths, list)\n\u001b[0;32m    301\u001b[0m           or any(not isinstance(p, str) for p in paths)):\n\u001b[1;32m--> 302\u001b[1;33m         raise ValueError(\n\u001b[0m\u001b[0;32m    303\u001b[0m             \"paths must be a path string or a list of path strings.\")\n\u001b[0;32m    304\u001b[0m     \u001b[1;32melif\u001b[0m \u001b[0mlen\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mpaths\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;33m==\u001b[0m \u001b[1;36m0\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mValueError\u001b[0m: paths must be a path string or a list of path strings."
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-12-05 19:47:05,375\tERROR worker.py:84 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): \u001b[36mray::_map_block()\u001b[39m (pid=1360, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\n",
      "  File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\n",
      "    new_block = fn(block)\n",
      "  File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\n",
      "    applied = fn(view)\n",
      "  File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\n",
      "  File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\n",
      "    raise KeyError(list(np.compress(check, subset)))\n",
      "KeyError: ['feature_1']\n"
     ]
    }
   ],
   "source": [
    "def train_func():\n",
    "    # This is a dummy train function just iterating over the dataset shard.\n",
    "    # You should replace this with your training logic.\n",
    "    shard = ray.train.get_dataset_shard()\n",
    "    for row in shard.iter_rows():\n",
    "        print(row)\n",
    "\n",
    "# Create a pipeline that loops over its source dataset indefinitely.\n",
    "pipe: DatasetPipeline = ray.data \\\n",
    "    .read_parquet(...) \\\n",
    "    .repeat() \\\n",
    "    .random_shuffle_each_window()\n",
    "\n",
    "\n",
    "# Pass in the pipeline to the Trainer.\n",
    "# The Trainer will automatically split the DatasetPipeline for you.\n",
    "trainer = Trainer(num_workers=8, backend=\"torch\")\n",
    "result = trainer.run(\n",
    "    train_func,\n",
    "    config={\"worker_batch_size\": 64, \"num_epochs\": 2},\n",
    "    dataset=pipe)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "7a564ccc",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " pid=13176)\u001b[0m 2021-12-05 19:48:05,087\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(ef25d802e8c24317ffffffffffffffffffffffff01000000).\n",
      " pid=13176)\u001b[0m Traceback (most recent call last):\n",
      " pid=13176)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\n",
      " pid=13176)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\n",
      " pid=13176)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\n",
      " pid=13176)\u001b[0m     new_block = fn(block)\n",
      " pid=13176)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\n",
      " pid=13176)\u001b[0m     applied = fn(view)\n",
      " pid=13176)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\n",
      " pid=13176)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\n",
      " pid=13176)\u001b[0m     return func(*args, **kwargs)\n",
      " pid=13176)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\n",
      " pid=13176)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\n",
      " pid=13176)\u001b[0m KeyError: ['feature_1']\n",
      " pid=1360)\u001b[0m 2021-12-05 19:48:05,113\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(b9c64831282591f9ffffffffffffffffffffffff01000000).\n",
      " pid=1360)\u001b[0m Traceback (most recent call last):\n",
      " pid=1360)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\n",
      " pid=1360)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\n",
      " pid=1360)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\n",
      " pid=1360)\u001b[0m     new_block = fn(block)\n",
      " pid=1360)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\n",
      " pid=1360)\u001b[0m     applied = fn(view)\n",
      " pid=1360)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\n",
      " pid=1360)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\n",
      " pid=1360)\u001b[0m     return func(*args, **kwargs)\n",
      " pid=1360)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\n",
      " pid=1360)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\n",
      " pid=1360)\u001b[0m KeyError: ['feature_1']\n",
      " pid=13328)\u001b[0m 2021-12-05 19:48:05,125\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(02bed209b72c305affffffffffffffffffffffff01000000).\n",
      " pid=13328)\u001b[0m Traceback (most recent call last):\n",
      " pid=13328)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\n",
      " pid=13328)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\n",
      " pid=13328)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\n",
      " pid=13328)\u001b[0m     new_block = fn(block)\n",
      " pid=13328)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\n",
      " pid=13328)\u001b[0m     applied = fn(view)\n",
      " pid=13328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\n",
      " pid=13328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\n",
      " pid=13328)\u001b[0m     return func(*args, **kwargs)\n",
      " pid=13328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\n",
      " pid=13328)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\n",
      " pid=13328)\u001b[0m KeyError: ['feature_1']\n",
      " pid=10020)\u001b[0m 2021-12-05 19:48:05,121\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(faf123d8b1b35293ffffffffffffffffffffffff01000000).\n",
      " pid=10020)\u001b[0m Traceback (most recent call last):\n",
      " pid=10020)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\n",
      " pid=10020)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\n",
      " pid=10020)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\n",
      " pid=10020)\u001b[0m     new_block = fn(block)\n",
      " pid=10020)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\n",
      " pid=10020)\u001b[0m     applied = fn(view)\n",
      " pid=10020)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\n",
      " pid=10020)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\n",
      " pid=10020)\u001b[0m     return func(*args, **kwargs)\n",
      " pid=10020)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\n",
      " pid=10020)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\n",
      " pid=10020)\u001b[0m KeyError: ['feature_1']\n",
      " pid=1360)\u001b[0m 2021-12-05 19:48:05,141\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(7fabc23126d27f51ffffffffffffffffffffffff01000000).\n",
      " pid=1360)\u001b[0m Traceback (most recent call last):\n",
      " pid=1360)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\n",
      " pid=1360)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\n",
      " pid=1360)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\n",
      " pid=1360)\u001b[0m     new_block = fn(block)\n",
      " pid=1360)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\n",
      " pid=1360)\u001b[0m     applied = fn(view)\n",
      " pid=1360)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\n",
      " pid=1360)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\n",
      " pid=1360)\u001b[0m     return func(*args, **kwargs)\n",
      " pid=1360)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\n",
      " pid=1360)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\n",
      " pid=1360)\u001b[0m KeyError: ['feature_1']\n",
      " pid=13176)\u001b[0m 2021-12-05 19:48:05,169\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(e07eebba574c5c52ffffffffffffffffffffffff01000000).\n",
      " pid=13176)\u001b[0m Traceback (most recent call last):\n",
      " pid=13176)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\n",
      " pid=13176)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\n",
      " pid=13176)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\n",
      " pid=13176)\u001b[0m     new_block = fn(block)\n",
      " pid=13176)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\n",
      " pid=13176)\u001b[0m     applied = fn(view)\n",
      " pid=13176)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\n",
      " pid=13176)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\n",
      " pid=13176)\u001b[0m     return func(*args, **kwargs)\n",
      " pid=13176)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\n",
      " pid=13176)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\n",
      " pid=13176)\u001b[0m KeyError: ['feature_1']\n",
      " pid=13176)\u001b[0m 2021-12-05 19:48:05,190\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(bde90c6e4585812cffffffffffffffffffffffff01000000).\n",
      " pid=13176)\u001b[0m Traceback (most recent call last):\n",
      " pid=13176)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\n",
      " pid=13176)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\n",
      " pid=13176)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\n",
      " pid=13176)\u001b[0m     new_block = fn(block)\n",
      " pid=13176)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\n",
      " pid=13176)\u001b[0m     applied = fn(view)\n",
      " pid=13176)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\n",
      " pid=13176)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\n",
      " pid=13176)\u001b[0m     return func(*args, **kwargs)\n",
      " pid=13176)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\n",
      " pid=13176)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\n",
      " pid=13176)\u001b[0m KeyError: ['feature_1']\n",
      " pid=1360)\u001b[0m 2021-12-05 19:48:05,202\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(85186699e206774effffffffffffffffffffffff01000000).\n",
      " pid=1360)\u001b[0m Traceback (most recent call last):\n",
      " pid=1360)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\n",
      " pid=1360)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\n",
      " pid=1360)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\n",
      " pid=1360)\u001b[0m     new_block = fn(block)\n",
      " pid=1360)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\n",
      " pid=1360)\u001b[0m     applied = fn(view)\n",
      " pid=1360)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\n",
      " pid=1360)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\n",
      " pid=1360)\u001b[0m     return func(*args, **kwargs)\n",
      " pid=1360)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\n",
      " pid=1360)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\n",
      " pid=1360)\u001b[0m KeyError: ['feature_1']\n",
      " pid=13328)\u001b[0m 2021-12-05 19:48:05,176\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(6c1e0b9bd7e2a3a6ffffffffffffffffffffffff01000000).\n",
      " pid=13328)\u001b[0m Traceback (most recent call last):\n",
      " pid=13328)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\n",
      " pid=13328)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\n",
      " pid=13328)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\n",
      " pid=13328)\u001b[0m     new_block = fn(block)\n",
      " pid=13328)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\n",
      " pid=13328)\u001b[0m     applied = fn(view)\n",
      " pid=13328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\n",
      " pid=13328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\n",
      " pid=13328)\u001b[0m     return func(*args, **kwargs)\n",
      " pid=13328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\n",
      " pid=13328)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\n",
      " pid=13328)\u001b[0m KeyError: ['feature_1']\n",
      " pid=10020)\u001b[0m 2021-12-05 19:48:05,173\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(6346e12fbb9bd273ffffffffffffffffffffffff01000000).\n",
      " pid=10020)\u001b[0m Traceback (most recent call last):\n",
      " pid=10020)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\n",
      " pid=10020)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\n",
      " pid=10020)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\n",
      " pid=10020)\u001b[0m     new_block = fn(block)\n",
      " pid=10020)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\n",
      " pid=10020)\u001b[0m     applied = fn(view)\n",
      " pid=10020)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\n",
      " pid=10020)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\n",
      " pid=10020)\u001b[0m     return func(*args, **kwargs)\n",
      " pid=10020)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\n",
      " pid=10020)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\n",
      " pid=10020)\u001b[0m KeyError: ['feature_1']\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m 2021-12-05 19:48:10,471\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(ef25d802e8c24317ffffffffffffffffffffffff01000000).\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m Traceback (most recent call last):\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m     new_block = fn(block)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m     applied = fn(view)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m     return func(*args, **kwargs)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m KeyError: ['feature_1']\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m 2021-12-05 19:48:10,492\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(e07eebba574c5c52ffffffffffffffffffffffff01000000).\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m Traceback (most recent call last):\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m     new_block = fn(block)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m     applied = fn(view)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m     return func(*args, **kwargs)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m KeyError: ['feature_1']\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m 2021-12-05 19:48:10,471\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(b9c64831282591f9ffffffffffffffffffffffff01000000).\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m Traceback (most recent call last):\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m     new_block = fn(block)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m     applied = fn(view)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m     return func(*args, **kwargs)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m KeyError: ['feature_1']\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m 2021-12-05 19:48:10,492\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(7fabc23126d27f51ffffffffffffffffffffffff01000000).\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m Traceback (most recent call last):\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m     new_block = fn(block)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m     applied = fn(view)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m     return func(*args, **kwargs)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m KeyError: ['feature_1']\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m 2021-12-05 19:48:10,484\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(faf123d8b1b35293ffffffffffffffffffffffff01000000).\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m Traceback (most recent call last):\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m     new_block = fn(block)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m     applied = fn(view)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m     return func(*args, **kwargs)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m KeyError: ['feature_1']\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m 2021-12-05 19:48:10,509\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(6c1e0b9bd7e2a3a6ffffffffffffffffffffffff01000000).\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m Traceback (most recent call last):\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m     new_block = fn(block)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m     applied = fn(view)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m     return func(*args, **kwargs)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m KeyError: ['feature_1']\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m 2021-12-05 19:48:10,472\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(02bed209b72c305affffffffffffffffffffffff01000000).\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m Traceback (most recent call last):\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m     new_block = fn(block)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m     applied = fn(view)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m     return func(*args, **kwargs)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m KeyError: ['feature_1']\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m 2021-12-05 19:48:10,492\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(6346e12fbb9bd273ffffffffffffffffffffffff01000000).\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m Traceback (most recent call last):\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m     new_block = fn(block)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m     applied = fn(view)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m     return func(*args, **kwargs)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m KeyError: ['feature_1']\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m 2021-12-05 19:48:10,515\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(85186699e206774effffffffffffffffffffffff01000000).\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m Traceback (most recent call last):\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m     new_block = fn(block)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m     applied = fn(view)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m     return func(*args, **kwargs)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m KeyError: ['feature_1']\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m 2021-12-05 19:48:10,509\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(bde90c6e4585812cffffffffffffffffffffffff01000000).\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m Traceback (most recent call last):\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m     new_block = fn(block)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m     applied = fn(view)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m     return func(*args, **kwargs)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m KeyError: ['feature_1']\r\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m 2021-12-05 19:48:16,489\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(02bed209b72c305affffffffffffffffffffffff01000000).\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m Traceback (most recent call last):\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m     new_block = fn(block)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m     applied = fn(view)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m     return func(*args, **kwargs)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m KeyError: ['feature_1']\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m 2021-12-05 19:48:16,514\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(e07eebba574c5c52ffffffffffffffffffffffff01000000).\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m Traceback (most recent call last):\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m     new_block = fn(block)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m     applied = fn(view)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m     return func(*args, **kwargs)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m KeyError: ['feature_1']\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m 2021-12-05 19:48:16,534\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(bde90c6e4585812cffffffffffffffffffffffff01000000).\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m Traceback (most recent call last):\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m     new_block = fn(block)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m     applied = fn(view)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m     return func(*args, **kwargs)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m KeyError: ['feature_1']\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=1360)\u001b[0m 2021-12-05 19:48:16,503\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(faf123d8b1b35293ffffffffffffffffffffffff01000000).\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=1360)\u001b[0m Traceback (most recent call last):\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=1360)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=1360)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=1360)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=1360)\u001b[0m     new_block = fn(block)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=1360)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=1360)\u001b[0m     applied = fn(view)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=1360)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=1360)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=1360)\u001b[0m     return func(*args, **kwargs)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=1360)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=1360)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=1360)\u001b[0m KeyError: ['feature_1']\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=1360)\u001b[0m 2021-12-05 19:48:16,533\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(85186699e206774effffffffffffffffffffffff01000000).\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=1360)\u001b[0m Traceback (most recent call last):\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=1360)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=1360)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=1360)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=1360)\u001b[0m     new_block = fn(block)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=1360)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=1360)\u001b[0m     applied = fn(view)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=1360)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=1360)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=1360)\u001b[0m     return func(*args, **kwargs)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=1360)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=1360)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=1360)\u001b[0m KeyError: ['feature_1']\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m 2021-12-05 19:48:16,492\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(b9c64831282591f9ffffffffffffffffffffffff01000000).\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m Traceback (most recent call last):\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m     new_block = fn(block)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m     applied = fn(view)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m     return func(*args, **kwargs)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m KeyError: ['feature_1']\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m 2021-12-05 19:48:16,521\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(7fabc23126d27f51ffffffffffffffffffffffff01000000).\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m Traceback (most recent call last):\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m     new_block = fn(block)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m     applied = fn(view)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m     return func(*args, **kwargs)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m KeyError: ['feature_1']\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m 2021-12-05 19:48:16,490\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(ef25d802e8c24317ffffffffffffffffffffffff01000000).\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m Traceback (most recent call last):\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m     new_block = fn(block)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m     applied = fn(view)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m     return func(*args, **kwargs)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m KeyError: ['feature_1']\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m 2021-12-05 19:48:16,514\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(6346e12fbb9bd273ffffffffffffffffffffffff01000000).\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m Traceback (most recent call last):\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m     new_block = fn(block)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m     applied = fn(view)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m     return func(*args, **kwargs)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m KeyError: ['feature_1']\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m 2021-12-05 19:48:16,534\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(6c1e0b9bd7e2a3a6ffffffffffffffffffffffff01000000).\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m Traceback (most recent call last):\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m     new_block = fn(block)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m     applied = fn(view)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m     return func(*args, **kwargs)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m KeyError: ['feature_1']\r\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m 2021-12-05 19:48:22,519\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(faf123d8b1b35293ffffffffffffffffffffffff01000000).\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m Traceback (most recent call last):\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m     new_block = fn(block)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m     applied = fn(view)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m     return func(*args, **kwargs)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=12328)\u001b[0m KeyError: ['feature_1']\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m 2021-12-05 19:48:22,504\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(02bed209b72c305affffffffffffffffffffffff01000000).\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m Traceback (most recent call last):\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m     new_block = fn(block)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m     applied = fn(view)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m     return func(*args, **kwargs)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13176)\u001b[0m KeyError: ['feature_1']\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m 2021-12-05 19:48:22,516\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(b9c64831282591f9ffffffffffffffffffffffff01000000).\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m Traceback (most recent call last):\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m     new_block = fn(block)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m     applied = fn(view)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m     return func(*args, **kwargs)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=13328)\u001b[0m KeyError: ['feature_1']\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m 2021-12-05 19:48:22,503\tINFO worker.py:431 -- Task failed with retryable exception: TaskID(ef25d802e8c24317ffffffffffffffffffffffff01000000).\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m Traceback (most recent call last):\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m     new_block = fn(block)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m     applied = fn(view)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m     return func(*args, **kwargs)\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m   File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m     raise KeyError(list(np.compress(check, subset)))\r\n",
      "\u001b[2m\u001b[36m(_map_block\r",
      " pid=10020)\u001b[0m KeyError: ['feature_1']\r\n"
     ]
    },
    {
     "ename": "RayTaskError(KeyError)",
     "evalue": "\u001b[36mray::_map_block()\u001b[39m (pid=13176, ip=127.0.0.1)\n  File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\n  File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\n  File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\n    new_block = fn(block)\n  File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\n    applied = fn(view)\n  File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\n  File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\n    return func(*args, **kwargs)\n  File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\n    raise KeyError(list(np.compress(check, subset)))\nKeyError: ['feature_1']",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mRayTaskError(KeyError)\u001b[0m                    Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m     18\u001b[0m \u001b[1;31m# batch_format=\"pandas\" tells Datasets to provide the transformer with blocks\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     19\u001b[0m \u001b[1;31m# represented as Pandas DataFrames.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 20\u001b[1;33m \u001b[0mds\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mds\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mmap_batches\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtransform_batch\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mbatch_format\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m\"pandas\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;32mD:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\u001b[0m in \u001b[0;36mmap_batches\u001b[1;34m(self, fn, batch_size, compute, batch_format, **ray_remote_args)\u001b[0m\n\u001b[0;32m    235\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    236\u001b[0m         return Dataset(\n\u001b[1;32m--> 237\u001b[1;33m             \u001b[0mcompute\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mapply\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtransform\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mray_remote_args\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_blocks\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    238\u001b[0m             self._epoch)\n\u001b[0;32m    239\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\u001b[0m in \u001b[0;36mapply\u001b[1;34m(self, fn, remote_args, blocks)\u001b[0m\n\u001b[0;32m     67\u001b[0m                     \u001b[1;32mpass\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     68\u001b[0m             \u001b[1;31m# Reraise the original task failure exception.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 69\u001b[1;33m             \u001b[1;32mraise\u001b[0m \u001b[0me\u001b[0m \u001b[1;32mfrom\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     70\u001b[0m         \u001b[1;32mreturn\u001b[0m \u001b[0mBlockList\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mlist\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mnew_blocks\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mlist\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mnew_metadata\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     71\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\u001b[0m in \u001b[0;36mapply\u001b[1;34m(self, fn, remote_args, blocks)\u001b[0m\n\u001b[0;32m     53\u001b[0m         \u001b[0mnew_metadata\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mlist\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mnew_metadata\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     54\u001b[0m         \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 55\u001b[1;33m             \u001b[0mnew_metadata\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mmap_bar\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfetch_until_complete\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mnew_metadata\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     56\u001b[0m         \u001b[1;32mexcept\u001b[0m \u001b[1;33m(\u001b[0m\u001b[0mray\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mexceptions\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mRayTaskError\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mKeyboardInterrupt\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     57\u001b[0m             \u001b[1;31m# One or more mapper tasks failed, or we received a SIGINT signal\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\progress_bar.py\u001b[0m in \u001b[0;36mfetch_until_complete\u001b[1;34m(self, refs)\u001b[0m\n\u001b[0;32m     56\u001b[0m         \u001b[1;32mwhile\u001b[0m \u001b[0mremaining\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     57\u001b[0m             \u001b[0mdone\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mremaining\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mray\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mwait\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mremaining\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfetch_local\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mTrue\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 58\u001b[1;33m             \u001b[1;32mfor\u001b[0m \u001b[0mref\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mresult\u001b[0m \u001b[1;32min\u001b[0m \u001b[0mzip\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mdone\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mray\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mdone\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     59\u001b[0m                 \u001b[0mref_to_result\u001b[0m\u001b[1;33m[\u001b[0m\u001b[0mref\u001b[0m\u001b[1;33m]\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mresult\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     60\u001b[0m             \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mupdate\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mlen\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mdone\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\u001b[0m in \u001b[0;36mwrapper\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m    103\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[0mfunc\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m__name__\u001b[0m \u001b[1;33m!=\u001b[0m \u001b[1;34m\"init\"\u001b[0m \u001b[1;32mor\u001b[0m \u001b[0mis_client_mode_enabled_by_default\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    104\u001b[0m                 \u001b[1;32mreturn\u001b[0m \u001b[0mgetattr\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mray\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfunc\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m__name__\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m*\u001b[0m\u001b[0margs\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 105\u001b[1;33m         \u001b[1;32mreturn\u001b[0m \u001b[0mfunc\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m*\u001b[0m\u001b[0margs\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    106\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    107\u001b[0m     \u001b[1;32mreturn\u001b[0m \u001b[0mwrapper\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\worker.py\u001b[0m in \u001b[0;36mget\u001b[1;34m(object_refs, timeout)\u001b[0m\n\u001b[0;32m   1711\u001b[0m                     \u001b[0mworker\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mcore_worker\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mdump_object_store_memory_usage\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1712\u001b[0m                 \u001b[1;32mif\u001b[0m \u001b[0misinstance\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mvalue\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mRayTaskError\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1713\u001b[1;33m                     \u001b[1;32mraise\u001b[0m \u001b[0mvalue\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mas_instanceof_cause\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1714\u001b[0m                 \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1715\u001b[0m                     \u001b[1;32mraise\u001b[0m \u001b[0mvalue\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mRayTaskError(KeyError)\u001b[0m: \u001b[36mray::_map_block()\u001b[39m (pid=13176, ip=127.0.0.1)\n  File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\n  File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\n  File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\n    new_block = fn(block)\n  File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\n    applied = fn(view)\n  File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\n  File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\n    return func(*args, **kwargs)\n  File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\n    raise KeyError(list(np.compress(check, subset)))\nKeyError: ['feature_1']"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-12-05 19:48:28,495\tERROR worker.py:84 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): \u001b[36mray::_map_block()\u001b[39m (pid=10020, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\n",
      "  File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\n",
      "    new_block = fn(block)\n",
      "  File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\n",
      "    applied = fn(view)\n",
      "  File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\n",
      "  File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\n",
      "    raise KeyError(list(np.compress(check, subset)))\n",
      "KeyError: ['feature_1']\n",
      "2021-12-05 19:48:28,498\tERROR worker.py:84 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): \u001b[36mray::_map_block()\u001b[39m (pid=13176, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\n",
      "  File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\n",
      "    new_block = fn(block)\n",
      "  File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\n",
      "    applied = fn(view)\n",
      "  File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\n",
      "  File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\n",
      "    raise KeyError(list(np.compress(check, subset)))\n",
      "KeyError: ['feature_1']\n",
      "2021-12-05 19:48:28,502\tERROR worker.py:84 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): \u001b[36mray::_map_block()\u001b[39m (pid=13328, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\n",
      "  File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\n",
      "    new_block = fn(block)\n",
      "  File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\n",
      "    applied = fn(view)\n",
      "  File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\n",
      "  File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\n",
      "    raise KeyError(list(np.compress(check, subset)))\n",
      "KeyError: ['feature_1']\n",
      "2021-12-05 19:48:28,509\tERROR worker.py:84 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): \u001b[36mray::_map_block()\u001b[39m (pid=12328, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 625, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 629, in ray._raylet.execute_task\n",
      "  File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\n",
      "    new_block = fn(block)\n",
      "  File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 220, in transform\n",
      "    applied = fn(view)\n",
      "  File \"C:\\Users\\James\\AppData\\Local\\Temp/ipykernel_13152/2366480439.py\", line 4, in transform_batch\n",
      "  File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\James\\AppData\\Roaming\\Python\\Python38\\site-packages\\pandas\\core\\frame.py\", line 5953, in dropna\n",
      "    raise KeyError(list(np.compress(check, subset)))\n",
      "KeyError: ['feature_1']\n",
      "2021-12-05 19:48:28,513\tERROR worker.py:84 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): \u001b[36mray::_map_block()\u001b[39m (pid=13176, ip=127.0.0.1)\n",
      "  File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\compute.py\", line 23, in _map_block\n",
      "    new_block = fn(block)\n",
      "  File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\dataset.py\", line 212, in transform\n",
      "    view = BlockAccessor.for_block(view).to_pandas()\n",
      "  File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\impl\\arrow_block.py\", line 224, in to_pandas\n",
      "    return self._table.to_pandas()\n",
      "  File \"pyarrow\\array.pxi\", line 766, in pyarrow.lib._PandasConvertible.to_pandas\n",
      "  File \"pyarrow\\table.pxi\", line 1815, in pyarrow.lib.Table._to_pandas\n",
      "  File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\pyarrow\\pandas_compat.py\", line 789, in table_to_blockmanager\n",
      "    blocks = _table_to_blocks(options, table, categories, ext_columns_dtypes)\n",
      "  File \"D:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\pyarrow\\pandas_compat.py\", line 1128, in _table_to_blocks\n",
      "    result = pa.lib.table_to_blocks(options, block_table, categories,\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\u001b[36mray::_map_block()\u001b[39m (pid=13176, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 618, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 650, in ray._raylet.execute_task\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(6346e12fbb9bd273ffffffffffffffffffffffff01000000) was cancelled\n"
     ]
    }
   ],
   "source": [
    "# A Pandas DataFrame UDF for transforming the underlying blocks of a Dataset in parallel.\n",
    "def transform_batch(df: pd.DataFrame):\n",
    "    # Drop nulls.\n",
    "    df = df.dropna(subset=[\"feature_1\"])\n",
    "    # Add new column.\n",
    "    df[\"new_col\"] = df[\"feature_1\"] - 2 * df[\"feature_2\"] + df[\"feature_3\"] / 3\n",
    "    # Transform existing column.\n",
    "    df[\"feature_1\"] = 2 * df[\"feature_1\"] + 1\n",
    "    # Drop column.\n",
    "    df.drop(columns=\"feature_2\", inplace=True)\n",
    "    # One-hot encoding.\n",
    "    categories = [\"cat_1\", \"cat_2\", \"cat_3\"]\n",
    "    for category in categories:\n",
    "        df[f\"category_{category}\"] = df[\"category\"].map(\n",
    "            collections.defaultdict(int, **{category: 1}))\n",
    "    return df\n",
    "\n",
    "# batch_format=\"pandas\" tells Datasets to provide the transformer with blocks\n",
    "# represented as Pandas DataFrames.\n",
    "ds = ds.map_batches(transform_batch, batch_format=\"pandas\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "f3cf36ef",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Sort Sample: 100%|██████████| 10/10 [00:00<00:00, 49.75it/s]\n",
      "GroupBy Map: 100%|██████████| 10/10 [00:00<00:00, 31.72it/s]\n",
      "GroupBy Reduce: 100%|██████████| 10/10 [00:00<00:00, 183.13it/s]\n",
      "GroupBy Map: 100%|██████████| 10/10 [00:00<00:00, 271.91it/s]\n",
      "GroupBy Reduce: 100%|██████████| 1/1 [00:00<00:00, 89.91it/s]\n",
      "GroupBy Map: 100%|██████████| 10/10 [00:00<00:00, 97.95it/s]\n",
      "GroupBy Reduce: 100%|██████████| 1/1 [00:00<00:00, 85.34it/s]\n",
      "GroupBy Map: 100%|██████████| 10/10 [00:00<00:00, 1009.90it/s]\n",
      "GroupBy Reduce: 100%|██████████| 1/1 [00:00<00:00, 73.55it/s]\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "{'mean(B)': 9.0, 'std(B)': 5.744562646538029, 'mean(C)': 13.5, 'std(C)': 8.616843969807043}"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "ds: ray.data.Dataset = ray.data.from_items([\n",
    "    {\"A\": x % 3, \"B\": 2 * x, \"C\": 3 * x}\n",
    "    for x in range(10)])\n",
    "\n",
    "# Group by the A column and calculate the per-group mean for B and C columns.\n",
    "agg_ds: ray.data.Dataset = ds.groupby(\"A\").mean([\"B\", \"C\"])\n",
    " \n",
    "agg_ds.to_pandas()\n",
    "\n",
    "# Global mean on B column.\n",
    "ds.mean(\"B\")\n",
    "\n",
    "# Global mean on multiple columns.\n",
    "ds.mean([\"B\", \"C\"])\n",
    "\n",
    "# Multiple global aggregations on multiple columns.\n",
    "from ray.data.aggregate import Mean, Std\n",
    "ds.aggregate(Mean(\"B\"), Std(\"B\", ddof=0), Mean(\"C\"), Std(\"C\", ddof=0))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "fef7c688",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "GroupBy Map: 100%|██████████| 10/10 [00:00<00:00, 140.28it/s]\n",
      "GroupBy Reduce: 100%|██████████| 1/1 [00:00<00:00, 60.09it/s]\n",
      "Map Progress: 100%|██████████| 10/10 [00:00<00:00, 95.72it/s]\n",
      "GroupBy Map: 100%|██████████| 10/10 [00:00<00:00, 507.13it/s]\n",
      "GroupBy Reduce: 100%|██████████| 1/1 [00:00<00:00, 37.30it/s]\n",
      "Map Progress: 100%|██████████| 10/10 [00:00<00:00, 67.85it/s]\n"
     ]
    }
   ],
   "source": [
    "# Impute missing values with the column mean.\n",
    "b_mean = ds.mean(\"B\")\n",
    "\n",
    "def impute_b(df: pd.DataFrame):\n",
    "    df[\"B\"].fillna(b_mean)\n",
    "    return df\n",
    "\n",
    "ds = ds.map_batches(impute_b, batch_format=\"pandas\")\n",
    "\n",
    "# Standard scaling of all feature columns.\n",
    "stats = ds.aggregate(Mean(\"B\"), Std(\"B\"), Mean(\"C\"), Std(\"C\"))\n",
    "\n",
    "def batch_standard_scaler(df: pd.DataFrame):\n",
    "    def column_standard_scaler(s: pd.Series):\n",
    "        s_mean = stats[f\"mean({s.name})\"]\n",
    "        s_std = stats[f\"std({s.name})\"]\n",
    "        return (s - s_mean) / s_std\n",
    "\n",
    "    cols = df.columns.difference([\"A\"])\n",
    "    df.loc[:, cols] = df.loc[:, cols].transform(column_standard_scaler)\n",
    "    return df\n",
    "\n",
    "ds = ds.map_batches(batch_standard_scaler, batch_format=\"pandas\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "fba85846",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Shuffle Map: 100%|██████████| 10/10 [00:00<00:00, 166.12it/s]\n",
      "Shuffle Reduce: 100%|██████████| 10/10 [00:00<00:00, 193.22it/s]\n",
      "Map Progress:   0%|          | 0/2 [02:32<?, ?it/s]\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp/ipykernel_13152/3188846593.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      9\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     10\u001b[0m \u001b[1;31m# Scales to terabytes of data with the same simple API.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 11\u001b[1;33m \u001b[0mds\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mray\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mdata\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mread_parquet\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"s3://ursa-labs-taxi-data\"\u001b[0m\u001b[1;33m)\u001b[0m  \u001b[1;31m# open, tabular, NYC taxi dataset\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     12\u001b[0m \u001b[1;31m# -> Dataset(num_blocks=125, num_rows=1547741381, schema={\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     13\u001b[0m \u001b[1;31m#        vendor_id: string, pickup_at: timestamp[us], dropoff_at: timestamp[us],\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\read_api.py\u001b[0m in \u001b[0;36mread_parquet\u001b[1;34m(paths, filesystem, columns, parallelism, ray_remote_args, _tensor_column_schema, **arrow_parquet_args)\u001b[0m\n\u001b[0;32m    269\u001b[0m         \u001b[0marrow_parquet_args\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m\"_block_udf\"\u001b[0m\u001b[1;33m]\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0m_block_udf\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    270\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 271\u001b[1;33m     return read_datasource(\n\u001b[0m\u001b[0;32m    272\u001b[0m         \u001b[0mParquetDatasource\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    273\u001b[0m         \u001b[0mparallelism\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mparallelism\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\read_api.py\u001b[0m in \u001b[0;36mread_datasource\u001b[1;34m(datasource, parallelism, ray_remote_args, _spread_resource_prefix, **read_args)\u001b[0m\n\u001b[0;32m    159\u001b[0m     \"\"\"\n\u001b[0;32m    160\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 161\u001b[1;33m     \u001b[0mread_tasks\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mdatasource\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mprepare_read\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mparallelism\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mread_args\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    162\u001b[0m     \u001b[0mcontext\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mDatasetContext\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget_current\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    163\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\datasource\\parquet_datasource.py\u001b[0m in \u001b[0;36mprepare_read\u001b[1;34m(self, parallelism, paths, filesystem, columns, schema, _block_udf, **reader_args)\u001b[0m\n\u001b[0;32m    129\u001b[0m             \u001b[0minferred_schema\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mschema\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    130\u001b[0m         \u001b[0mread_tasks\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;33m[\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 131\u001b[1;33m         \u001b[0mserialized_pieces\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;33m[\u001b[0m\u001b[0mcloudpickle\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mdumps\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mp\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;32mfor\u001b[0m \u001b[0mp\u001b[0m \u001b[1;32min\u001b[0m \u001b[0mpq_ds\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpieces\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    132\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mlen\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mpq_ds\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpieces\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;33m>\u001b[0m \u001b[0mPARALLELIZE_META_FETCH_THRESHOLD\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    133\u001b[0m             \u001b[0mmetadata\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0m_fetch_metadata_remotely\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mserialized_pieces\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\data\\datasource\\parquet_datasource.py\u001b[0m in \u001b[0;36m<listcomp>\u001b[1;34m(.0)\u001b[0m\n\u001b[0;32m    129\u001b[0m             \u001b[0minferred_schema\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mschema\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    130\u001b[0m         \u001b[0mread_tasks\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;33m[\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 131\u001b[1;33m         \u001b[0mserialized_pieces\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;33m[\u001b[0m\u001b[0mcloudpickle\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mdumps\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mp\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;32mfor\u001b[0m \u001b[0mp\u001b[0m \u001b[1;32min\u001b[0m \u001b[0mpq_ds\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpieces\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    132\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mlen\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mpq_ds\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpieces\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;33m>\u001b[0m \u001b[0mPARALLELIZE_META_FETCH_THRESHOLD\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    133\u001b[0m             \u001b[0mmetadata\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0m_fetch_metadata_remotely\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mserialized_pieces\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\cloudpickle\\cloudpickle_fast.py\u001b[0m in \u001b[0;36mdumps\u001b[1;34m(obj, protocol, buffer_callback)\u001b[0m\n\u001b[0;32m     71\u001b[0m                 \u001b[0mfile\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mprotocol\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mprotocol\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mbuffer_callback\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mbuffer_callback\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     72\u001b[0m             )\n\u001b[1;32m---> 73\u001b[1;33m             \u001b[0mcp\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mdump\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mobj\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     74\u001b[0m             \u001b[1;32mreturn\u001b[0m \u001b[0mfile\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mgetvalue\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     75\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\cloudpickle\\cloudpickle_fast.py\u001b[0m in \u001b[0;36mdump\u001b[1;34m(self, obj)\u001b[0m\n\u001b[0;32m    618\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0mdump\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mobj\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    619\u001b[0m         \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 620\u001b[1;33m             \u001b[1;32mreturn\u001b[0m \u001b[0mPickler\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mdump\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mobj\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    621\u001b[0m         \u001b[1;32mexcept\u001b[0m \u001b[0mRuntimeError\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    622\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[1;34m\"recursion\"\u001b[0m \u001b[1;32min\u001b[0m \u001b[0me\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0margs\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\anaconda3\\envs\\yourenvname\\lib\\site-packages\\ray\\cloudpickle\\cloudpickle_fast.py\u001b[0m in \u001b[0;36mreducer_override\u001b[1;34m(self, obj)\u001b[0m\n\u001b[0;32m    662\u001b[0m             \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mproto\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mprotocol\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    663\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 664\u001b[1;33m         \u001b[1;32mdef\u001b[0m \u001b[0mreducer_override\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mobj\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    665\u001b[0m             \"\"\"Type-agnostic reducing callback for function and classes.\n\u001b[0;32m    666\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "ds = ray.data.range(10)\n",
    "# -> [0, 1, ..., 9]\n",
    "\n",
    "# Global random shuffle.\n",
    "ds = ds.random_shuffle()\n",
    "\n",
    "# Scales to terabytes of data with the same simple API.\n",
    "ds = ray.data.read_parquet(\"s3://ursa-labs-taxi-data\")  # open, tabular, NYC taxi dataset\n",
    "\n",
    "# Don't run this next one on your laptop; it will probably crash since it will\n",
    "# try to read and shuffle ~99 GB of data!\n",
    "ds = ds.random_shuffle()\n",
    "\n",
    "# Per-epoch shuffling is as simple as changing where we invoke the shuffle:\n",
    "#   - Before repeating => dataset is shuffled once.\n",
    "#   - After repeating  => dataset is shuffled on every epoch.\n",
    "num_epochs = 20\n",
    "\n",
    "# Shuffle once, then repeat this once-shuffled dataset for num_epochs epochs.\n",
    "ds.random_shuffle().repeat(num_epochs)\n",
    "\n",
    "# Shuffle repeatedly, where the original dataset is shuffled into a different\n",
    "# order at the beginning of each epoch.\n",
    "ds.repeat(num_epochs).random_shuffle_each_window()\n",
    "# -> DatasetPipeline(num_windows=10, num_stages=2)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "03af5ad5",
   "metadata": {},
   "source": [
    "Dask"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "4fd514e2",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-12-05 19:50:18,098\tINFO worker.py:852 -- Calling ray.init() again after it has already been called.\n"
     ]
    }
   ],
   "source": [
    "import ray\n",
    "from ray.util.dask import ray_dask_get\n",
    "import dask\n",
    "import dask.array as da\n",
    "import dask.dataframe as dd\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    "# Start Ray.\n",
    "# Tip: If connecting to an existing cluster, use ray.init(address=\"auto\").\n",
    "ray.init(ignore_reinit_error=True)\n",
    "\n",
    "d_arr = da.from_array(np.random.randint(0, 1000, size=(256, 256)))\n",
    "\n",
    "# The Dask scheduler submits the underlying task graph to Ray.\n",
    "d_arr.mean().compute(scheduler=ray_dask_get)\n",
    "\n",
    "# Set the scheduler to ray_dask_get in your config so you don't have to\n",
    "# specify it on each compute call.\n",
    "dask.config.set(scheduler=ray_dask_get)\n",
    "\n",
    "df = dd.from_pandas(\n",
    "    pd.DataFrame(\n",
    "        np.random.randint(0, 100, size=(1024, 2)), columns=[\"age\", \"grade\"]),\n",
    "    npartitions=2)\n",
    "df.groupby([\"age\"]).mean().compute()\n",
    "\n",
    "ray.shutdown()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "9787a2c0",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div><strong>Dask DataFrame Structure:</strong></div>\n",
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>age</th>\n",
       "      <th>grade</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>npartitions=2</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>int32</td>\n",
       "      <td>int32</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>512</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1023</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>\n",
       "<div>Dask Name: from_pandas, 2 tasks</div>"
      ],
      "text/plain": [
       "Dask DataFrame Structure:\n",
       "                 age  grade\n",
       "npartitions=2              \n",
       "0              int32  int32\n",
       "512              ...    ...\n",
       "1023             ...    ...\n",
       "Dask Name: from_pandas, 2 tasks"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
